GET http://localhost:5228/games

###
GET http://localhost:5228/games/2

###
POST http://localhost:5228/games
Content-Type: application/json

{
    "name" : "Final Fantasy XIV",
    "genreId":2,
    "price":9.99,
    "releaseDate":"2011-11-18"
}

###
PUT http://localhost:5228/games/3
Content-Type: application/json

{
    "name" : "Street Fighter",
    "genreId":1 ,
    "price":9.99,
    "releaseDate":"2011-11-18"
}

###
DELETE http://localhost:5228/games/1


