services:
  backend:
    build: 
      context: ./GameStore.Api
      dockerfile: Dockerfile
    ports:
      - "5274:5274"
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5274
    volumes:
      - sqlite_data:/app/Data
    restart: always

  frontend:
    build:
      context: ./GameStore.Frontend
      dockerfile: DockerFile
    ports:
      - "5002:8080"
    depends_on:
      - backend
    restart: always

volumes:
  sqlite_data:
